/**
 * Description Form Component
 *
 * Provides a form for creating and editing descriptions with multi-language
 * translations and neighborhood associations.
 */

'use client'

import { useState } from 'react'

/**
 * Constants
 */
// Textarea rows sized for 150-300 character descriptions (typical community story length)
const DESCRIPTION_TEXTAREA_ROWS = 8
import { useRouter } from 'next/navigation'
import { useTranslations } from 'next-intl'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Textarea } from '@/components/ui/textarea'
import { Badge } from '@/components/ui/badge'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  createDescription,
  updateDescription,
  type DescriptionFormData,
  type DescriptionTranslationData,
} from '@/app/actions/descriptions'

/**
 * Language data structure
 */
interface Language {
  id: string
  endonym: string | null
  translations: Array<{ name: string; locale_code: string }>
}

/**
 * Neighborhood data structure
 */
interface Neighborhood {
  id: string
  slug: string
  translations: Array<{ name: string; locale_code: string }>
}

/**
 * Translation data structure
 */
interface Translation {
  text: string
  locale: string
  is_ai_translated: boolean
  ai_model: string | null
}

/**
 * Existing description data for editing
 */
interface ExistingDescription {
  id: string
  language_id: string
  neighborhood_id: string | null
  is_ai_generated: boolean
  ai_model: string | null
  translations: Translation[]
}

interface DescriptionFormProps {
  citySlug: string
  locale: string
  languages: Language[]
  neighborhoods: Neighborhood[]
  existingDescription?: ExistingDescription
  mode: 'create' | 'edit'
}

/**
 * DescriptionForm component
 *
 * Renders a form for creating or editing descriptions with validation.
 * Supports both create and edit modes with different behaviors for each mode.
 * In create mode, allows setting description text. In edit mode, only metadata can be changed.
 *
 * @param props - Component props
 * @param props.citySlug - The slug of the city (e.g., 'amsterdam', 'paris')
 * @param props.locale - The current locale code for UI language (e.g., 'en', 'nl', 'fr')
 * @param props.languages - Available languages for selection. Each language object contains:
 *   - id: UUID of the language
 *   - endonym: Language name in its own language (not translated)
 *   - translations: Array of translated names, each with name and locale_code
 * @param props.neighborhoods - Available neighborhoods for optional association. Each contains:
 *   - id: UUID of the neighborhood
 *   - slug: URL-friendly identifier
 *   - translations: Array of translated names, each with name and locale_code
 * @param props.existingDescription - Existing description data for edit mode (undefined in create mode). Contains:
 *   - id: UUID of the description
 *   - language_id: UUID of the associated language
 *   - neighborhood_id: UUID of the neighborhood (nullable)
 *   - is_ai_generated: Whether this description was generated by AI
 *   - ai_model: Model used for generation (if AI-generated)
 *   - translations: Array of translation objects with text, locale, and AI metadata
 * @param props.mode - Form mode: 'create' for new descriptions, 'edit' for updating existing metadata
 * @returns React functional component rendering the description form
 */
export function DescriptionForm({
  citySlug,
  locale,
  languages,
  neighborhoods,
  existingDescription,
  mode,
}: DescriptionFormProps) {
  // Input validation - validate props at component entry
  if (!citySlug || typeof citySlug !== 'string' || citySlug.trim() === '') {
    throw new Error('citySlug is required and must be a non-empty string')
  }

  if (!locale || typeof locale !== 'string' || locale.trim() === '') {
    throw new Error('locale is required and must be a non-empty string')
  }

  if (!Array.isArray(languages)) {
    throw new Error('languages must be an array')
  }

  if (!Array.isArray(neighborhoods)) {
    throw new Error('neighborhoods must be an array')
  }

  if (mode !== 'create' && mode !== 'edit') {
    throw new Error('mode must be "create" or "edit"')
  }

  // If in edit mode, existingDescription is required
  if (mode === 'edit' && !existingDescription) {
    throw new Error('existingDescription is required when mode is "edit"')
  }

  const t = useTranslations('descriptions')
  const router = useRouter()

  // Find current translation
  const currentTranslation = existingDescription?.translations.find(
    (trans) => trans.locale === locale
  )

  // Form state
  const [formData, setFormData] = useState<DescriptionFormData>({
    language_id: existingDescription?.language_id || '',
    neighborhood_id: existingDescription?.neighborhood_id || null,
    is_ai_generated: existingDescription?.is_ai_generated || false,
    ai_model: existingDescription?.ai_model || null,
  })

  const [descriptionText, setDescriptionText] = useState<string>(
    currentTranslation?.text || ''
  )

  const [isSubmitting, setIsSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  /**
   * Handles form field changes
   */
  const handleChange = (
    field: keyof DescriptionFormData,
    value: string | boolean | null
  ) => {
    setFormData((prev) => ({ ...prev, [field]: value }))
  }

  /**
   * Handles form submission
   *
   * @param e - Form event
   */
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsSubmitting(true)
    setError(null)

    try {
      // Validate description text
      if (!descriptionText || descriptionText.trim() === '') {
        throw new Error(t('form.errorTextRequired'))
      }

      if (mode === 'create') {
        // Create new description with initial translation
        const initialTranslation: DescriptionTranslationData = {
          locale,
          text: descriptionText,
          is_ai_translated: false,
          ai_model: null,
        }

        await createDescription(citySlug, formData, initialTranslation)
        router.push(`/${locale}/operator/${citySlug}/descriptions`)
      } else if (existingDescription) {
        // Update description metadata only
        await updateDescription(citySlug, existingDescription.id, formData)
        router.push(`/${locale}/operator/${citySlug}/descriptions`)
      }
    } catch (err) {
      console.error('Error submitting description form:', {
        citySlug,
        mode,
        languageId: formData.language_id,
        neighborhoodId: formData.neighborhood_id,
        hasDescriptionText: !!descriptionText,
        descriptionLength: descriptionText.length,
        error: err instanceof Error ? err.message : 'Unknown error',
        stack: err instanceof Error ? err.stack : undefined,
      })
      setError(err instanceof Error ? err.message : t('form.errorGeneric'))
    } finally {
      setIsSubmitting(false)
    }
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-6">
      {error && (
        <div className="rounded-md bg-red-50 p-4 text-sm text-red-800">
          {error}
        </div>
      )}

      {/* Language Selection */}
      <div className="space-y-2">
        <Label htmlFor="language_id">{t('form.language')}</Label>
        <Select
          value={formData.language_id}
          onValueChange={(value) => handleChange('language_id', value)}
          disabled={mode === 'edit'}
        >
          <SelectTrigger id="language_id">
            <SelectValue placeholder={t('form.selectLanguage')} />
          </SelectTrigger>
          <SelectContent>
            {languages.map((language) => (
              <SelectItem key={language.id} value={language.id}>
                {language.translations[0]?.name || language.endonym || 'Unknown'}
                {language.endonym && language.translations[0]?.name && (
                  <span className="ml-2 text-muted-foreground">
                    ({language.endonym})
                  </span>
                )}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
        {mode === 'edit' && (
          <p className="text-sm text-muted-foreground">
            {t('form.languageCannotChange')}
          </p>
        )}
      </div>

      {/* Neighborhood Selection (Optional) */}
      <div className="space-y-2">
        <Label htmlFor="neighborhood_id">
          {t('form.neighborhood')} ({t('form.optional')})
        </Label>
        <Select
          value={formData.neighborhood_id || 'none'}
          onValueChange={(value) =>
            handleChange('neighborhood_id', value === 'none' ? null : value)
          }
        >
          <SelectTrigger id="neighborhood_id">
            <SelectValue placeholder={t('form.selectNeighborhood')} />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="none">{t('form.noNeighborhood')}</SelectItem>
            {neighborhoods.map((neighborhood) => (
              <SelectItem key={neighborhood.id} value={neighborhood.id}>
                {neighborhood.translations[0]?.name || neighborhood.slug}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      {/* Description Text */}
      <div className="space-y-2">
        <Label htmlFor="text">
          {t('form.description')}
          {currentTranslation?.is_ai_translated && (
            <Badge variant="secondary" className="ml-2">
              {t('form.aiTranslated')}
            </Badge>
          )}
        </Label>
        <Textarea
          id="text"
          value={descriptionText}
          onChange={(e) => setDescriptionText(e.target.value)}
          placeholder={t('form.descriptionPlaceholder')}
          rows={DESCRIPTION_TEXTAREA_ROWS}
          className="w-full"
          disabled={mode === 'edit'}
        />
        {mode === 'edit' && (
          <p className="text-sm text-muted-foreground">
            {t('form.useTranslationsPage')}
          </p>
        )}
        {mode === 'create' && (
          <p className="text-sm text-muted-foreground">
            {t('form.descriptionHint', { locale: locale.toUpperCase() })}
          </p>
        )}
      </div>

      {/* AI Generation Badge (if applicable) */}
      {existingDescription?.is_ai_generated && (
        <div className="rounded-md bg-blue-50 p-4">
          <div className="flex items-center gap-2">
            <Badge variant="secondary">{t('form.aiGenerated')}</Badge>
            {existingDescription.ai_model && (
              <span className="text-sm text-muted-foreground">
                {t('form.model')}: {existingDescription.ai_model}
              </span>
            )}
          </div>
        </div>
      )}

      {/* Form Actions */}
      <div className="flex gap-4">
        <Button type="submit" disabled={isSubmitting}>
          {isSubmitting
            ? t('form.saving')
            : mode === 'create'
              ? t('form.create')
              : t('form.update')}
        </Button>
        <Button
          type="button"
          variant="outline"
          onClick={() => router.push(`/${locale}/operator/${citySlug}/descriptions`)}
          disabled={isSubmitting}
        >
          {t('form.cancel')}
        </Button>
      </div>
    </form>
  )
}
