-- ============================================
-- DESCRIPTIONS (MULTI-LINGUAL)
-- ============================================
-- Migration: Create descriptions and description_translations tables
-- Date: 2025-11-12
-- Description: Descriptions are community stories about languages, linked to neighborhoods

-- Descriptions (community stories)
CREATE TABLE IF NOT EXISTS descriptions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  city_id UUID NOT NULL REFERENCES cities(id) ON DELETE CASCADE,
  language_id UUID NOT NULL REFERENCES languages(id) ON DELETE CASCADE,
  neighborhood_id UUID REFERENCES neighborhoods(id),

  -- AI generation tracking
  is_ai_generated BOOLEAN NOT NULL DEFAULT false,
  ai_model TEXT,                           -- 'gpt-4', 'claude-3-opus', etc.
  ai_generated_at TIMESTAMPTZ,
  reviewed_by UUID REFERENCES user_profiles(id),
  reviewed_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES user_profiles(id)
);

-- Description Translations
CREATE TABLE IF NOT EXISTS description_translations (
  description_id UUID NOT NULL REFERENCES descriptions(id) ON DELETE CASCADE,
  locale TEXT NOT NULL REFERENCES locales(code),
  text TEXT NOT NULL,

  -- AI translation tracking
  is_ai_translated BOOLEAN NOT NULL DEFAULT false,
  ai_model TEXT,
  ai_translated_at TIMESTAMPTZ,
  reviewed_by UUID REFERENCES user_profiles(id),
  reviewed_at TIMESTAMPTZ,

  PRIMARY KEY (description_id, locale)
);

-- ============================================
-- INDEXES
-- ============================================

CREATE INDEX IF NOT EXISTS idx_descriptions_city_id ON descriptions(city_id);
CREATE INDEX IF NOT EXISTS idx_descriptions_language_id ON descriptions(language_id);
CREATE INDEX IF NOT EXISTS idx_descriptions_neighborhood_id ON descriptions(neighborhood_id);
CREATE INDEX IF NOT EXISTS idx_description_translations_locale ON description_translations(locale);

-- ============================================
-- ROW-LEVEL SECURITY (RLS)
-- ============================================

ALTER TABLE descriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE description_translations ENABLE ROW LEVEL SECURITY;

-- Public read access for published content
CREATE POLICY "Public can read descriptions"
  ON descriptions FOR SELECT
  USING (true);

CREATE POLICY "Public can read description translations"
  ON description_translations FOR SELECT
  USING (true);

-- City users (operators/admins/superusers) can manage descriptions
CREATE POLICY "City users can manage descriptions"
  ON descriptions FOR ALL
  USING (
    auth.uid() IN (
      SELECT user_id FROM city_users WHERE city_id = descriptions.city_id
      UNION
      SELECT id FROM user_profiles WHERE role = 'superuser'
    )
  );

CREATE POLICY "City users can manage description translations"
  ON description_translations FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM descriptions d
      WHERE d.id = description_translations.description_id
      AND (
        auth.uid() IN (
          SELECT user_id FROM city_users WHERE city_id = d.city_id
          UNION
          SELECT id FROM user_profiles WHERE role = 'superuser'
        )
      )
    )
  );

-- ============================================
-- TRIGGERS
-- ============================================

-- Auto-update updated_at timestamp
CREATE OR REPLACE FUNCTION update_descriptions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER descriptions_updated_at
  BEFORE UPDATE ON descriptions
  FOR EACH ROW
  EXECUTE FUNCTION update_descriptions_updated_at();

-- ============================================
-- COMMENTS
-- ============================================

COMMENT ON TABLE descriptions IS 'Community stories about languages, linked to neighborhoods';
COMMENT ON TABLE description_translations IS 'Translations of descriptions in different locales';
COMMENT ON COLUMN descriptions.is_ai_generated IS 'Whether this description was generated by AI';
COMMENT ON COLUMN descriptions.ai_model IS 'AI model used for generation (e.g., gpt-4, claude-3-opus)';
COMMENT ON COLUMN description_translations.is_ai_translated IS 'Whether this translation was generated by AI';
COMMENT ON COLUMN description_translations.ai_model IS 'AI model used for translation';
